# Generated by Django 5.0.6 on 2024-09-22 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='file_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('docx', 'DOCX'), ('link', 'Link')], max_length=50)),
                ('file_size', models.IntegerField()),
                ('is_temp', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='lessons.lesson')),
            ],
        ),
    ]
