# Generated by Django 5.0.6 on 2024-10-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_file_size_remove_lesson_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlink',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lessonlink',
            name='link_url',
            field=models.URLField(),
        ),
    ]
