# Generated by Django 5.1.6 on 2025-05-18 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0003_course_intro_video_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoomMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("topic", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("meeting_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "meeting_password",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("join_url", models.URLField(blank=True, max_length=500, null=True)),
                ("start_time", models.DateTimeField()),
                ("duration", models.IntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("canceled", "Canceled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("host_video", models.BooleanField(default=True)),
                ("participant_video", models.BooleanField(default=True)),
                ("join_before_host", models.BooleanField(default=False)),
                ("mute_upon_entry", models.BooleanField(default=True)),
                (
                    "auto_recording",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("local", "Local"),
                            ("cloud", "Cloud"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("settings_json", models.JSONField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zoom_meetings",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ZoomMeetingParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("time_in_meeting", models.IntegerField(default=0)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="zoom.zoommeeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zoom_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="zoommeeting",
            index=models.Index(
                fields=["course"], name="zoom_zoomme_course__c8ac5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zoommeeting",
            index=models.Index(
                fields=["created_by"], name="zoom_zoomme_created_9ffedc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zoommeeting",
            index=models.Index(
                fields=["start_time"], name="zoom_zoomme_start_t_a4a39c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zoommeeting",
            index=models.Index(fields=["status"], name="zoom_zoomme_status_1c772f_idx"),
        ),
        migrations.AddIndex(
            model_name="zoommeetingparticipant",
            index=models.Index(
                fields=["meeting", "user"], name="zoom_zoomme_meeting_2007ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zoommeetingparticipant",
            index=models.Index(
                fields=["joined_at"], name="zoom_zoomme_joined__4f2e39_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="zoommeetingparticipant",
            unique_together={("meeting", "user")},
        ),
    ]
