# Generated by Django 5.0.6 on 2024-07-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_teacher_ef24fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_start_d_2c5b9f_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
