# Generated by Django 5.0.6 on 2024-09-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_courses_cou_teacher_ef24fb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_video_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
